### ISSUE TITLE
Using github releases instead of embedded file links?

### ISSUE THREAD

**Issue by chenrui333** [Saxonica/Saxon-HE#1]
👋 I see the artifact has been relocated from sourceforge into github, I am curious why you dont use github release instead of embedded file links? (You can create a release tag and upload artifacts into it). Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/120597

**Comment by ndw** [comment]
That is a good idea. Frankly, there were [about 800 moving parts](https://so.nwalsh.com/2023/01/13-saxon12) for the Saxon 12.0 release, including getting things moved off SourceForge. Constructing a release by hand just didn't make it onto my todo list.

I will investigate next week.

**Comment by chenrui333** [comment]
> including getting things moved off SourceForge.

i think that can be done later, sourceforge is not shutting soon, right?

> Constructing a release by hand just didn't make it onto my todo list.

In github world, there is github action to help automate this, and there is some action like https://github.com/softprops/action-gh-release would help with uploading release artifacts.

**Comment by michaelhkay** [comment]
> think that can be done later, sourceforge is not shutting soon, right?

The essential step was that if we weren't going to put new stuff on SourceForge, we need to make it clear to any SourceForge visitors that they need to look elsewhere.

But I don't trust SourceForge any more as a long-term archive of historic material. There are old releases I can't find there any more. There used to be stuff that was available to administrators but not to ordinary users, but it seems to have gone. And even if the stuff is there, negotiating your way past all the adware to find it is a nightmare.

**Comment by chenrui333** [comment]
> > think that can be done later, sourceforge is not shutting soon, right?
> 
> The essential step was that if we weren't going to put new stuff on SourceForge, we need to make it clear to any SourceForge visitors that they need to look elsewhere.
> 
> But I don't trust SourceForge any more as a long-term archive of historic material. There are old releases I can't find there any more. There used to be stuff that was available to administrators but not to ordinary users, but it seems to have gone. And even if the stuff is there, negotiating your way past all the adware to find it is a nightmare.

totally agree, i find sourceforge experience really bad to find right information as user. (there is search on the site)

**Comment by ndw** [comment]
Done.
