### ISSUE TITLE
Saxon HE 12 seems to require JDK 11

### ISSUE THREAD

**Issue by chrjohn** [Saxonica/Saxon-HE#2]
On https://www.saxonica.com/documentation12/#!about/installationjava/prerequisites it is stated that

> SaxonJ 12 is built and tested using Java SE 11, but should also still be usable with Java 8

Maybe it hasn't been compiled with the correct release option since it seems to require JDK 11 and not 8:

```
bad class file: /home/runner/.m2/repository/net/sf/saxon/Saxon-HE/12.0/Saxon-HE-12.0.jar(net/sf/saxon/TransformerFactoryImpl.class) 
 class file has wrong version 55.0, should be 52.0
```

**Comment by michaelhkay** [comment]
This has been noted, and logged at https://saxonica.plan.io/issues/5824.

Pleae note that the place for Saxon issues is at https://saxonica.plan.io/.

**Comment by chrjohn** [comment]
Ok thanks. Might be worth noting this in the README and/ or disable issues for this repo.

**Comment by ndw** [comment]
Yes, I've made myself a TODO to fix this.
