### ISSUE TITLE
PyPI: Examples #3 / #4 (XSLT) do not fit to version

### ISSUE THREAD

**Issue by DummerJunge** [Saxonica/Saxon-HE#3]
See https://pypi.org/project/saxonche/:  `xsltproc.set_source(xdm_node=document)`  seems to be outdated, or?

**Comment by michaelhkay** [comment]
Please note that Saxon issues are tracked at https://saxonica.plan.io/

**Comment by DummerJunge** [comment]
Thanks for your note, perhaps you may [disable the issue tracker](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/disabling-issues), nevertheless I have no account on plan.io.

**Comment by ond1** [comment]
Hi, Thanks for reporting the problem. I have created the issue: https://saxonica.plan.io/issues/5917 and fixed the examples accordingly. You can register on plan.io here: https://saxonica.plan.io/account/register
