### ISSUE TITLE
Cannot unzip the downloaded file from this repo

### ISSUE THREAD

**Issue by rizwaan08** [Saxonica/Saxon-HE#4]
Archive:  SaxonHE10-3J.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of SaxonHE10-3J.zip or
        SaxonHE10-3J.zip.zip, and cannot find SaxonHE10-3J.zip.ZIP, period.

**Comment by rizwaan08** [comment]
I used the command 
wget https://github.com/Saxonica/Saxon-HE/blob/main/12/Java/SaxonHE10-3J.zip
unzip SaxonHE10-3J.zip

**Comment by michaelhkay** [comment]
I'm a bit surprised you find anything at that URL. Have you tried

https://github.com/Saxonica/Saxon-HE/blob/main/10/Java/SaxonHE10-3J.zip

**Comment by ndw** [comment]
In order to download a binary file directly from GitHub, you have to put `/raw/` in the URI. Try:
```
wget https://github.com/Saxonica/Saxon-HE/raw/main/10/Java/SaxonHE10-3J.zip
```
That's the link you'll find behind the "download" button if you navigate to the page.

**Comment by ndw** [comment]
(Sorry, I didn't actually mean to click "close" but I'm pretty confident this will fix the problem for you. Please reopen it if you continue to have trouble!)

**Comment by rizwaan08** [comment]
Thank you @ndw , it worked after inserting raw in the URI
