### ISSUE TITLE
Zip file download problem

### ISSUE THREAD

**Issue by simonjwright** [Saxonica/Saxon-HE#5]
I’m using Safari on an M1 Macbook Air, and on downloading SaxonHE12-2J.zip (right button, Download Linked File) what I got was a 5 kb file SaxonHE12-2J.zip.txt.

I managed to get the real thing by downloading the whole repo!

**Comment by michaelhkay** [comment]
I've had the same problem myself. There is a way of doing it without downloading the whole repo, but GitHub doesn't make it easy to find the right buttons. We'll discuss and see if we can find a solution.

**Comment by ndw** [comment]
Right. We need to use the releases mechanism.

**Comment by ndw** [comment]
I've added the latest releases to the releases tab, where they're easier to download, and added a note to the top-level README file about how to download zip files generally.

**Comment by simonjwright** [comment]
Thanks for this.

Re: the README changes, on Safari there’s no "Download" button, nor is there a "download raw file icon" link on the right hand side of the page.

**Comment by ndw** [comment]
That is really strange. I'm perplexed by UX differences on a per-browser basis. Here's what I see in Safari:

![safari](https://github.com/Saxonica/Saxon-HE/assets/36793/5115a1b4-624e-48fc-adfb-8aeff4106be2)

And Chrome:

![chrome](https://github.com/Saxonica/Saxon-HE/assets/36793/86d5aa65-6850-4b39-ab0e-a4bc9f449f01)

And Firefox:

![firefox](https://github.com/Saxonica/Saxon-HE/assets/36793/21279b64-3915-4702-85e7-4234b15a36f1)

Firefox is the odd one out here, with no "Download" button. What do you see in Safari, @simonjwright ?

**Comment by simonjwright** [comment]
Apologies.

My route to getting it wrong was
>on downloading SaxonHE12-2J.zip (right button, Download Linked File) what I got was a 5 kb file SaxonHE12-2J.zip.txt.

Thinking about it, your approach is exactly what one would do with a source file - but then, of course, one sees the source :-(

Sorry for the noise.
