### ISSUE TITLE
Add to conda-forge repository

### ISSUE THREAD

**Issue by munechika-koyo** [Saxonica/Saxon-HE#9]
Hello!

In order to facilitate installing `saxon-he` for conda-ecosystem users, I would like to suggest to upload it to the conda-forge repository.
I am sorry for letting you know nothing, but I already made the [PR](https://github.com/conda-forge/staged-recipes/pull/27833), ready to deploy.
Currently, I am only listed as a maintainer for its "recipe," so I would appreciate it if you would propose any potential members.

Many thanks for considering my request.

The official issue tracker for Saxonica products is [saxonica.plan.io](https://saxonica.plan.io/). Please only use the issue tracker here at GitHub to report issues with the Saxon-HE distribution archives in this repository.

**Comment by michaelhkay** [comment]
It's open source software so you can do what you like with it (provided of course that you read and follow the license conditions). You don't need our approval. Saxon-HE is built into hundreds of other packages, most of which (like Conda) we have never heard of.

We would encourage you to do it in a way that keeps up with new versions and maintenance releases as they appear.

**Comment by fidothe** [comment]
We're working on our Python infrastructure tooling at the moment, and Conda is on our radar, but we haven't figured out how PE and EE might fit into that too, as well as precisely which Saxon version (java or python) would be appropriate for Conda. 

I'll take a look at your PR/recipe with interest and we'll try and address conda-forge more directly when we're a bit further along with our work.

Thanks for taking an interest!

**Comment by munechika-koyo** [comment]
@michaelhkay Thank you for your kind response! I will merge it as soon as the conda-forge maintainer approves my [PR](https://github.com/conda-forge/staged-recipes/pull/27833).
Now I have the conda-forge distribution tied to the asset `[SaxonHE12-5J.zip](https://github.com/Saxonica/Saxon-HE/releases/download/SaxonHE12-5/SaxonHE12-5J.zip)` in GitHub release. If you upload a new release, conda-forge automatically detects it and changes the link to the new one.
So, it seems like there's no need to worry about it too much.

@fidothe Thank you for your informative comments!
Conda-ecosystem is mainly focusing on Python/R users but includes many other packages like C/C++, Fortran, etc. (of course java!)
Here is the helpful blog for conda-forge: https://prefix.dev/blog/towards_a_vendor_lock_in_free_conda_experience

My motivation is to use `Saxon-HE` for one of the `java` libraries, which is used in a build process for a certain package.
I am willing to contribute to your project!

**Comment by munechika-koyo** [comment]
Finally, `saxon-he` was uploaded to `conda-forge` repository.
The recipe that controls building and uploading the conda package can be seen here: https://github.com/conda-forge/saxon-he-feedstock
So, I am going to close this issue. Please discuss anything in its repository, if any.
